services:
  # ingestion:
  #   build:
  #     context: .
  #     dockerfile: services/ingestion/Dockerfile
  #   ports:
  #     - "7860:7860"
  #   env_file: .env
  #   volumes:
  #     - ./artifacts:/app/artifacts

  # transformation:
  #   build:
  #     context: .
  #     dockerfile: services/transformation/Dockerfile
  #   ports:
  #     - "7860:7860"
  #   env_file: .env
  #   volumes:
  #     - ./artifacts:/app/artifacts
  #   depends_on:
  #     - ingestion

  app:
    build: .
    image: pneumonia-seg
    ports:
      - "7860:7860"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"

  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - app

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
