services:
  ingestion:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    ports:
      - "7861:7860"
    env_file: .env
    volumes:
      - ./artifacts:/app/artifacts

  transformation:
    build:
      context: .
      dockerfile: services/transformation/Dockerfile
    ports:
      - "7862:7860"
    env_file: .env
    volumes:
      - ./artifacts:/app/artifacts
    depends_on:
      - ingestion

  data_drift:
    build:
      context: .
      dockerfile: services/data_drift/Dockerfile
    ports:
      - "7863:7860"
    env_file: .env
    volumes:
      - ./artifacts:/app/artifacts
    depends_on:
      - transformation

  # prepare_base_model:
  #   build:
  #     context: .
  #     dockerfile: services/prepare_base_model/Dockerfile
  #   ports:
  #     - "7864:7860"
  #   env_file: .env
  #   volumes:
  #     - ./artifacts:/app/artifacts

  # training:
  #   build:
  #     context: .
  #     dockerfile: services/training/Dockerfile
  #   ports:
  #     - "7865:7860"
  #   env_file: .env
  #   volumes:
  #     - ./artifacts:/app/artifacts
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   depends_on:
  #     - transformation

  # onnx_export:
  #   build:
  #     context: .
  #     dockerfile: services/onnx_export/Dockerfile
  #   ports:
  #     - "7866:7860"
  #   env_file: .env
  #   volumes:
  #     - ./artifacts:/app/artifacts
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  prefect:
    image: prefecthq/prefect:3-latest
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0

  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    ports:
      - "7867:7860"
    env_file: .env
    depends_on:
      - prefect
      - ingestion
      - transformation
      - data_drift

  # --------------------------- INFERENCE ---------------------------
  # app:
  #   build: .
  #   image: pneumonia-seg
  #   ports:
  #     - "7860:7860"
  #   env_file:
  #     - .env
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2g
  #         cpus: "1.0"

  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - app

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
