data_transformation_params:
  image_size: 512
  skip_background_ratio: 0.8
  slice_interval: 4
  valid_size: 0.1
  infer_size: 0.1

data_drift_params:
  drift_threshold: 50.0
  n_bins: 512
  max_samples: null
  seed: 42
  model_name: "resnet50"

prepare_base_model_params:
  model_architecture: "Unet"
  library: "segmentation_models_pytorch"
  model_name: "sam2unet"
  encoder: "mit_b2"
  encoder_weights: "imagenet"
  classes: 1
  activation: "None"

training_params:
  lr: 0.0001
  batch_size: 4
  decay: 0.0005
  patience: 5
  start_epoch: 0
  epochs: 21
  workers: 8
  seed: 42
  image_size: 352
  is_augmentation: True
  metric_mode: "max"
  loss_function: "focal-loss"
  lr_scheduler: "OneCycleLR"
  alpha: 0.25
  gamma: 2.0

onnx_params:
  image_size: 512

evaluation_params:
  batch_size: 8
  workers: 4
  image_size: 512
  is_augmentation: False
  threshold: 0.5

tensorRT_params:
  batch_size: 8
  image_size: 512

lstm_params:
  input_steps: 30
  output_steps: 5
  input_size: 4
  hidden_size: 128
  num_layers: 3
  epochs: 500
  batch_size: 32
  lr: 0.001

dqn_planner_params:
  n_metrics: 4 # cpu, ram, latency, drift
  output_steps: 5 # must equal to lstm_params.output_steps
  action_size: 5
  hidden_size: 128
  lr: 0.001
  gamma: 0.99
  epsilon: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  batch_size: 64
  target_update_freq: 100

simulation_params:
  cpu_warning: 80
  cpu_critical: 95
  ram_warning: 80
  ram_critical: 95
  latency_warning: 0.5
  latency_critical: 1.0
  drift_warning: 0.3
  drift_critical: 0.5
  output_steps: 5 # must equal to lstm_params.output_steps
