apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "app"
        static_configs:
          - targets: ["app:7860"]

      - job_name: "ingestion"
        static_configs:
          - targets: ["ingestion:7860"]

      - job_name: "transformation"
        static_configs:
          - targets: ["transformation:7860"]

      - job_name: "data-drift"
        static_configs:
          - targets: ["data-drift:7860"]
      
      - job_name: "orchestrator"
        static_configs:
          - targets: ["orchestrator:7860"]

      - job_name: "lstm"
        static_configs:
          - targets: ["lstm:7860"]

      - job_name: "dqn"
        static_configs:
          - targets: ["dqn:7860"]

      - job_name: "claude-validation"
        static_configs:
          - targets: ["claude-validation:7860"]
          
      - job_name: "ai-manager"
        static_configs:
          - targets: ["ai-manager:7860"]
          