artifacts_root: artifacts

data_ingestion_config:
  root_dir: artifacts/data_ingestion

data_transformation_config:
  root_dir: artifacts/data_transformation
  out_train_dir: artifacts/data_transformation/train
  out_valid_dir: artifacts/data_transformation/valid
  out_infer_dir: artifacts/data_transformation/infer

data_drift_config:
  root_dir: artifacts/data_drift

prepare_base_model_config:
  root_dir: artifacts/prepare_base_model

training_config:
  root_dir: artifacts/training

onnx_config:
  root_dir: artifacts/onnx

evaluation_config:
  root_dir: artifacts/evaluation

tensorRT_config:
  root_dir: artifacts/tensorRT

lstm_config:
  root_dir: artifacts/lstm

dqn_planner_config:
  root_dir: artifacts/dqn_planner
