apiVersion: apps/v1
kind: Deployment
metadata:
  name: lstm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lstm
  template:
    metadata:
      labels:
        app: lstm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "7860"
        prometheus.io/path:   "/metrics"
    spec:
      containers:
        - name: lstm
          image: bill123mk/pneumonia_mlops:lstm
          imagePullPolicy: Always
          ports:
            - containerPort: 7860
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
            - name: MODEL_DIR
              value: "/app/artifacts/lstm"
          envFrom:
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: artifacts
              mountPath: /app/artifacts
          readinessProbe:
            httpGet:
              path: /health
              port: 7860
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7860
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: artifacts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lstm
spec:
  selector:
    app: lstm
  ports:
    - port: 7860
      targetPort: 7860
  type: ClusterIP
