apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: bill123mk/pneumonia_mlops:orchestrator
          imagePullPolicy: Always
          ports:
            - containerPort: 7860
          envFrom:
            - secretRef:
                name: app-secrets
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
    - port: 7860
      targetPort: 7860
  type: ClusterIP
